version: "3.9"

services:
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask
    command: gunicorn --bind 0.0.0.0:5000 --workers 6 "app.app:create_app()"
    volumes:
      - ./:/var/www
    expose:
      - 5000
    networks:
      my-network:
        aliases:
          - flask-app

networks:
  my-network: